server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: kartingrm
          uri: lb://kartingrm:8090
          predicates:
            - Path=/api/mono/**
        - id: ms1-reservation-categories
          uri: lb://ms1-reservation-categories:8091
          predicates:
            - Path=/api/reservation-category/**
        - id: ms2-quantity-discounts
          uri: lb://ms2-quantity-discounts:8092
          predicates:
            - Path=/api/quantity-discount/**