server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms5-reservations
          uri: lb://ms5-reservations
          predicates:
            - Path=/api/mono/**
        - id: ms1-reservation-categories
          uri: lb://ms1-reservation-categories
          predicates:
            - Path=/api/reservation-category/**
        - id: ms2-quantity-discounts
          uri: lb://ms2-quantity-discounts
          predicates:
            - Path=/api/quantity-discount/**
        - id: ms3-frequency-discounts
          uri: lb://ms3-frequency-discounts
          predicates:
            - Path=/api/frequency-discount/**
        - id: ms4-special-tariffs
          uri: lb://ms4-special-tariffs
          predicates:
            - Path=/api/special-tariff/**