apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3-frequency-discounts
  labels:
    app: ms3-frequency-discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms3-frequency-discounts
  template:
    metadata:
      labels:
        app: ms3-frequency-discounts
    spec:
      containers:
        - name: ms3-frequency-discounts
          image: tingeso2clusterregistry.azurecr.io/ms3-frequency-discounts:latest
          ports:
            - containerPort: 8093
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: EUREKA_SERVER_HOST
              value: "eureka-server-service"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_MS3
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: project-secrets
                  key: DB_PASS