apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms6-rack
  labels:
    app: ms6-rack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms6-rack
  template:
    metadata:
      labels:
        app: ms6-rack
    spec:
      containers:
        - name: ms6-rack
          image: tingeso2clusterregistry.azurecr.io/ms6-rack:latest
          ports:
            - containerPort: 8096
          env:
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: EUREKA_SERVER_HOST
              value: "eureka-server-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"