apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms7-reports
  labels:
    app: ms7-reports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms7-reports
  template:
    metadata:
      labels:
        app: ms7-reports
    spec:
      containers:
        - name: ms7-reports
          image: tingeso2clusterregistry.azurecr.io/ms7-reports:latest
          ports:
            - containerPort: 8097
          env:
            - name: CONFIG_SERVER_HOST
              value: "config-server-service"
            - name: EUREKA_SERVER_HOST
              value: "eureka-server-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"